# Default values for home-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @section Common parameters

## @param nameOverride String to partially override common.names.name
##
nameOverride: ""

## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""

## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}

## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}

controller:
  # type: options are deployment, daemonset or statefulset
  type: deployment

  revisionHistoryLimit: 10
  replicas: 1
  strategy:
    ## For Deployments, valid values are Recreate and RollingUpdate
    ## For StatefulSets, valid values are OnDelete and RollingUpdate
    ## DaemonSets ignore this
    type: RollingUpdate

  ## @param deploy.containerPorts.http instance http port
  ##
  # containerPorts:
  #   http: 8080

  ## deploy image 
  ## @param deploy.image.repository deploy image repository
  ## @param deploy.image.tag deploy image tag (immutable tags are recommended)
  ## @param deploy.image.pullPolicy deploy image pull policy
  ##
  image:
    repository: ""
    tag: ""
    pullPolicy: IfNotPresent
    termination: {}
    securityContext: {}
    containerPorts:
      http: 334
    # command: []
    # args: []
    # lifecycle: {}
    ## https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
    # env:
    #   - name: LOG_LEVEL
    #     value: info
    # envFrom:
    #   - configMapRef:
    #       name: appconfig
    ## https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits-of-pod-and-container
    # resources:
    #   limits:
    #     cpu: "1"
    #   requests:
    #     cpu: "0.5"
    # volumeMounts:
    #   - name: test
    #     mountPath: /test
    #     # https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath
    #     subPath: path
    #     readOnly: false
    #     # https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation
    #     mountPropagation: None
  volumes: []

service:

ingress:
  enabled: false

  pathType: ImplementationSpecific
  className: "traefik"
  annotations: {}

  hostname: ""
  path: /

  