---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ include "common.names.fullname" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "common.names.name" . | quote }}
spec:
  replicas: {{ .Values.controller.replicas }}
  revisionHistoryLimit: {{ .Values.controller.revisionHistoryLimit }}
  strategy:
    {{- .Values.controller.strategy | toYaml | nindent 4 }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "common.names.name" . | quote }}
      
  template:
    metadata:
      namespace: {{ .Release.Namespace | quote }}
      name: {{ include "common.names.fullname" . | quote }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "common.names.name" . | quote }}
    spec:
      containers:
        {{- include "common.controller.container" $ | nindent 8 }}

      volumes: 
        {{- .Values.controller.volumes | toYaml | nindent 8 }}