apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-lab-helm.fullname" . }}-minio
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-lab-helm.labels" (dict "context" $ "name" "minio" "component" "object-store") | nindent 4 }}
spec:
  type: {{ .Values.minio.service.type }}
  selector:
    {{- include "data-lab-helm.selectorLabels" (dict "context" $ "name" "minio") | nindent 4 }}
  ports:
    - name: s3
      port: 9000
      targetPort: s3
      {{- if and (eq .Values.minio.service.type "NodePort") .Values.minio.service.apiNodePort }}
      nodePort: {{ .Values.minio.service.apiNodePort }}
      {{- end }}
    - name: console
      port: 9001
      targetPort: console
      {{- if and (eq .Values.minio.service.type "NodePort") .Values.minio.service.consoleNodePort }}
      nodePort: {{ .Values.minio.service.consoleNodePort }}
      {{- end }}
