apiVersion: v2
name: affine-helm
description: A Helm chart for Affine workspace application
type: application
version: 0.5.0
appVersion: "stable"
keywords:
  - affine
  - workspace
  - collaboration
home: https://affine.pro/
sources:
  - https://github.com/toeverything/AFFiNE
  - https://github.com/jfms7s/helm-charts
maintainers:
  - name: jfms7s
    url: https://github.com/jfms7s
