apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-affine-postgres
  labels:
    app.kubernetes.io/name: affine
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  postgres-password: {{ include "affine.postgres.password" . | b64enc }}
  openai-api-key: {{ .Values.openai.apiKey | default "none" | b64enc }}
