apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: affine
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: server
  name: {{ .Release.Name }}-affine
spec:
  ports:
    - name: http
      port: 3010
      targetPort: 3010
      protocol: TCP
  selector:
    app.kubernetes.io/name: affine
    app.kubernetes.io/instance: {{ .Release.Name }}