apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: affine
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: server
  name: {{ .Release.Name }}-affine
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: affine
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: affine
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: server
    spec:
      containers:
        - env:
            - name: AFFINE_INDEXER_ENABLED
              value: "false"
            - name: DATABASE_URL
              value: postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ .Release.Name }}-postgres:5432/{{ .Values.postgres.db }}
            - name: REDIS_SERVER_HOST
              value: {{ .Release.Name }}-redis
            - name: OPENAI_API_KEY
              value: {{ .Values.openai.apiKey | default "none" }}
            - name: OPENAI_BASE_URL
              value: {{ .Values.openai.baseUrl }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: affine-server
          ports:
            - containerPort: 3010
              protocol: TCP
          volumeMounts:
            - mountPath: /root/.affine/storage
              name: affine-storage
            - mountPath: /root/.affine/config
              name: affine-config
      restartPolicy: Always
      volumes:
        - name: affine-config
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.nfs.configPath }}
        - name: affine-storage
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.nfs.storagePath }}