apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: affine
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: migration
  name: {{ .Release.Name }}-affine-migration
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: affine
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: migration
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: affine
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: migration
    spec:
      containers:
        - args:
            - sh
            - -c
            - node ./scripts/self-host-predeploy.js
          env:
            - name: AFFINE_INDEXER_ENABLED
              value: "false"
            - name: DATABASE_URL
              value: postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ .Release.Name }}-postgres:5432/{{ .Values.postgres.db }}
            - name: REDIS_SERVER_HOST
              value: {{ .Release.Name }}-redis
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: affine-migration-job
          volumeMounts:
            - mountPath: /root/.affine/storage
              name: affine-storage
            - mountPath: /root/.affine/config
              name: affine-config
      restartPolicy: Always
      volumes:
        - name: affine-config
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.nfs.configPath }}
        - name: affine-storage
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.nfs.storagePath }}