---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: affine
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
    - host: affine.k3s.dragonbyte.myds.me
      http:
        paths:
          - path: "/"
            pathType: "ImplementationSpecific"
            backend: 
              service:
                name: affine
                port:
                  number: 3010
