{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-affine-postgres
  labels:
    {{- include "affine-helm.labels" (dict "context" $ "name" "affine" "component" "server") | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ include "affine-helm.postgres.password" . | b64enc }}
{{- end }}
