apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-affine
  labels:
    {{- include "affine-helm.labels" (dict "context" $ "name" "affine" "component" "server") | nindent 4 }}
spec:
  ports:
    - name: http
      port: 3010
      targetPort: 3010
      protocol: TCP
  selector:
    {{- include "affine-helm.selectorLabels" (dict "context" $ "name" "affine") | nindent 4 }}
