apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-affine-migration
  labels:
    {{- include "affine-helm.labels" (dict "context" $ "name" "affine" "component" "migration") | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  backoffLimit: 6
  template:
    metadata:
      labels:
        {{- include "affine-helm.labels" (dict "context" $ "name" "affine" "component" "migration") | nindent 8 }}
    spec:
      containers:
        - name: affine-migration-job
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - sh
            - -c
            - node ./scripts/self-host-predeploy.js
          env:
            - name: AFFINE_INDEXER_ENABLED
              value: "false"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "affine-helm.postgres.secretName" . }}
                  key: {{ include "affine-helm.postgres.secretKey" . }}
            - name: DATABASE_URL
              value: postgresql://{{ .Values.postgres.user }}:$(POSTGRES_PASSWORD)@{{ .Release.Name }}-postgres:5432/{{ .Values.postgres.db }}
            - name: REDIS_SERVER_HOST
              value: {{ .Release.Name }}-redis
          volumeMounts:
            - mountPath: /root/.affine/storage
              name: affine-storage
            - mountPath: /root/.affine/config
              name: affine-config
      restartPolicy: OnFailure
      volumes:
        - name: affine-config
          {{- if .Values.persistence.config.volume }}
          {{- toYaml .Values.persistence.config.volume | nindent 10 }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: affine-storage
          {{- if .Values.persistence.storage.volume }}
          {{- toYaml .Values.persistence.storage.volume | nindent 10 }}
          {{- else }}
          emptyDir: {}
          {{- end }}
