apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    {{- include "affine-helm.labels" (dict "context" $ "name" "postgres" "component" "database") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "affine-helm.selectorLabels" (dict "context" $ "name" "postgres") | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "affine-helm.labels" (dict "context" $ "name" "postgres" "component" "database") | nindent 8 }}
    spec:
      containers:
        - name: affine-postgres
          image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db }}
            - name: POSTGRES_HOST_AUTH_METHOD
              value: md5
            - name: POSTGRES_INITDB_ARGS
              value: --data-checksums
            - name: POSTGRES_PASSWORD
              {{- include "affine-helm.credentialEnv" .Values.postgres.password | nindent 14 }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.user }}
                - -d
                - {{ .Values.postgres.db }}
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.user }}
                - -d
                - {{ .Values.postgres.db }}
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      restartPolicy: Always
      volumes:
        - name: postgres-data
          {{- if .Values.postgres.persistence.volume }}
          {{- toYaml .Values.postgres.persistence.volume | nindent 10 }}
          {{- else }}
          emptyDir: {}
          {{- end }}
