apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: cache
  name: {{ .Release.Name }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: cache
    spec:
      containers:
        - image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
          livenessProbe:
            exec:
              command:
                - redis-cli
                - --raw
                - incr
                - ping
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: affine-redis
      restartPolicy: Always