apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    {{- include "affine-helm.labels" (dict "context" $ "name" "redis" "component" "cache") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "affine-helm.selectorLabels" (dict "context" $ "name" "redis") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "affine-helm.labels" (dict "context" $ "name" "redis" "component" "cache") | nindent 8 }}
    spec:
      containers:
        - name: affine-redis
          image: {{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          livenessProbe:
            exec:
              command:
                - redis-cli
                - --raw
                - incr
                - ping
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - redis-cli
                - --raw
                - incr
                - ping
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
      restartPolicy: Always
