apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-patchmon-postgres
  labels:
    {{- include "patchmon-helm.labels" (dict "context" $ "name" "postgres" "component" "database") | nindent 4 }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    {{- include "patchmon-helm.selectorLabels" (dict "context" $ "name" "postgres") | nindent 4 }}
