apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-patchmon-redis
  labels:
    {{- include "patchmon-helm.labels" (dict "context" $ "name" "redis" "component" "cache") | nindent 4 }}
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    {{- include "patchmon-helm.selectorLabels" (dict "context" $ "name" "redis") | nindent 4 }}
