apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-patchmon-redis
  labels:
    {{- include "patchmon-helm.labels" (dict "context" $ "name" "redis" "component" "cache") | nindent 4 }}
type: Opaque
data:
  redis-password: {{ include "patchmon-helm.redis.password" . | b64enc }}
