apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-patchmon-server
  labels:
    {{- include "patchmon-helm.labels" (dict "context" $ "name" "server" "component" "server") | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ include "patchmon-helm.server.jwtSecret" . | b64enc }}
  session-secret: {{ include "patchmon-helm.server.sessionSecret" . | b64enc }}
  ai-encryption-key: {{ include "patchmon-helm.server.aiEncryptionKey" . | b64enc }}
