apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-ticket-scanner-scraper
  labels:
    {{- include "ticket-live-event-scanner-helm.labels" (dict "context" $ "name" "scraper" "component" "scraper") | nindent 4 }}
