apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-budget-manager-web
  labels:
    {{- include "budget-manager-helm.labels" (dict "context" $ "name" "web" "component" "frontend") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "budget-manager-helm.selectorLabels" (dict "context" $ "name" "web") | nindent 4 }}
